# Generated by Django 5.0.4 on 2024-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.UUIDField(auto_created=True, default='0f8826d8-02c7-4fe0-a9a0-a7607d940261', editable=False, primary_key=True, serialize=False),
        ),
    ]
